#!/usr/bin/env bash
#print number 1 to 20 using loop

i=1
while [ $i -le 20 ]
do
	if [ $i -eq 4 ]; then
		 echo -e "$i \nbad luck from China"
	elif	[ $i -eq 9 ]; then
		echo  -e "$i \nbad luck from Japan"
	elif	[ $i -eq 17 ]; then
		echo  -e "$i \nbad luck from Italy"
	else
		echo $i
	fi
	((i++))
done
